version: '3.9'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:14.8-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    
  backend:
    image: aragon1025/foodgram_backend:latest
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file: .env
    restart: always
  
  frontend:
    image: aragon1025/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/


  gateway:
    image: aragon1025/foodgram_gateway
    env_file: .env
    ports:
      - "9090:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend
    restart: always

