version: '3.9'

services:
  db:
    image: postgres:14.8-bullseye
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    image: aragon1025/foodgram_backend:latest
    volumes:
      - static_value:/app/static_django/
      - media_value:/app/media/
    depends_on:
      - db
    env_file: ./.env
  
  frontend:
    env_file: .env
    image: aragon1025/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static_django
      - media_value:/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
