version: '3.9'

volumes:
  postgres_data:
  static:
  media:
  docs_volume:

services:
  db:
    image: postgres:14.8-bullseye
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    image: aragon1025/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs_volume:/app/docs

  frontend:
    image: aragon1025/foodgram_frontend:latest
    restart: always
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - docs_volume:/usr/share/nginx/html/api/docs/
      - media:/media
