version: '3.9'

services:
  db:
    image: postgres:14.8-bullseye
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  backend:
    image: aragon1025/foodgram_backend:latest
    restart: always
    volumes:
      - data_value:/code/data/
      - static_value:/app/static_backend/
      - media_value:/code/media/
    depends_on:
      - db
    env_file: ./.env
  
  frontend:
    env_file: .env
    image: aragon1025/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 7000:7000
    volumes:
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
