version: '3.9'
services:

  db:
    image: postgres:14.8-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: aragon1025/foodgram_backend:latest
    restart: always
    volumes:
      - data_value:/code/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    image: aragon1025/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  
  nginx:
    image: nginx:1.19.3
    ports:
      - 8090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
