version: '3.9'

services:
  db:
    image: postgres:14.8-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    

  
  frontend:
    image: aragon1025/foodgram_frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

  backend:
    image: aragon1025/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app_backend/static/
      - media_value:/app_backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn foodgram.wsgi:application --bind 0:8000"

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:

