version: '3.9'

services:
  db:
    image: postgres:14.8-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    

  backend:
    image: aragon1025/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../data:/data
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: aragon1025/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app/
      - static_value:/frontend_static/
      - media_value:/app/media/


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    command: ["nginx", "-c", "/etc/nginx/nginx.conf"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
  redoc:

