# Generated by Django 3.2 on 2024-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240321_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Длинна пароля не более 150', max_length=150, verbose_name='Пароль'),
        ),
    ]
